export type JugadorMapa = {
  id: number;
  nombre: string;
  edad: number;
  posicion: string;
  club: string;
  departamento: string;
  ciudad: string;
  lat: number;
  lng: number;
  rating: number;
};

/** Demo — interior de Uruguay (sin capital), plantel masculino juvenil. Reemplazá o conectá a Supabase cuando tengas datos reales. */
export const JUGADORES_MAPA_DEMO: JugadorMapa[] = [
  {
    id: 1,
    nombre: "Matías Rodríguez",
    edad: 16,
    posicion: "Delantero",
    club: "Atlético Artigas",
    departamento: "Artigas",
    ciudad: "Artigas",
    lat: -30.4015,
    lng: -56.4675,
    rating: 8.2,
  },
  {
    id: 2,
    nombre: "Carlos Viera",
    edad: 15,
    posicion: "Mediocampista",
    club: "Bella Unión FC",
    departamento: "Artigas",
    ciudad: "Bella Unión",
    lat: -30.266,
    lng: -57.583,
    rating: 7.4,
  },
  {
    id: 3,
    nombre: "Sebastián Lima",
    edad: 17,
    posicion: "Defensor",
    club: "Rivera United",
    departamento: "Rivera",
    ciudad: "Rivera",
    lat: -30.9053,
    lng: -55.5511,
    rating: 7.5,
  },
  {
    id: 4,
    nombre: "Nicolás Silvera",
    edad: 16,
    posicion: "Arquero",
    club: "Deportivo Tranqueras",
    departamento: "Rivera",
    ciudad: "Tranqueras",
    lat: -31.698,
    lng: -55.282,
    rating: 7.9,
  },
  {
    id: 5,
    nombre: "Franco Gómez",
    edad: 15,
    posicion: "Mediocampista",
    club: "Club Salto FC",
    departamento: "Salto",
    ciudad: "Salto",
    lat: -31.3833,
    lng: -57.9667,
    rating: 7.8,
  },
  {
    id: 6,
    nombre: "Agustín Pereira",
    edad: 17,
    posicion: "Delantero",
    club: "Salto Norte",
    departamento: "Salto",
    ciudad: "Constitución",
    lat: -31.232,
    lng: -57.832,
    rating: 8.0,
  },
  {
    id: 7,
    nombre: "Joaquín Bentancur",
    edad: 16,
    posicion: "Defensor",
    club: "Paysandú Wanderers Juv.",
    departamento: "Paysandú",
    ciudad: "Paysandú",
    lat: -32.321,
    lng: -58.076,
    rating: 7.6,
  },
  {
    id: 8,
    nombre: "Martín López",
    edad: 15,
    posicion: "Mediocampista",
    club: "Atlético Quebracho",
    departamento: "Paysandú",
    ciudad: "Quebracho",
    lat: -31.95,
    lng: -57.85,
    rating: 7.1,
  },
  {
    id: 9,
    nombre: "Lucas Correa",
    edad: 17,
    posicion: "Delantero",
    club: "Fray Bentos Athletic",
    departamento: "Río Negro",
    ciudad: "Fray Bentos",
    lat: -33.134,
    lng: -58.304,
    rating: 7.7,
  },
  {
    id: 10,
    nombre: "Valentín Núñez",
    edad: 16,
    posicion: "Mediocampista",
    club: "Juventud Mercedes",
    departamento: "Soriano",
    ciudad: "Mercedes",
    lat: -33.252,
    lng: -58.03,
    rating: 8.1,
  },
  {
    id: 11,
    nombre: "Santiago Rossi",
    edad: 15,
    posicion: "Defensor",
    club: "Dolores FC",
    departamento: "Soriano",
    ciudad: "Dolores",
    lat: -33.53,
    lng: -58.217,
    rating: 6.9,
  },
  {
    id: 12,
    nombre: "Pablo Santana",
    edad: 16,
    posicion: "Arquero",
    club: "Trinidad Unión",
    departamento: "Flores",
    ciudad: "Trinidad",
    lat: -33.517,
    lng: -56.883,
    rating: 7.3,
  },
  {
    id: 13,
    nombre: "Ignacio Cabrera",
    edad: 17,
    posicion: "Delantero",
    club: "Durazno FC",
    departamento: "Durazno",
    ciudad: "Durazno",
    lat: -33.383,
    lng: -56.517,
    rating: 8.4,
  },
  {
    id: 14,
    nombre: "Francisco Castro",
    edad: 15,
    posicion: "Mediocampista",
    club: "Sarandí del Yí",
    departamento: "Durazno",
    ciudad: "Sarandí del Yí",
    lat: -33.35,
    lng: -55.95,
    rating: 7.0,
  },
  {
    id: 15,
    nombre: "Diego Acosta",
    edad: 16,
    posicion: "Lateral",
    club: "Florida Oeste",
    departamento: "Florida",
    ciudad: "Florida",
    lat: -34.084,
    lng: -56.214,
    rating: 7.2,
  },
];
